// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballApp.Migrations
{
    [DbContext(typeof(FootballLeagueContext))]
    [Migration("20250527153954_MakeTeamNullableForPlayer")]
    partial class MakeTeamNullableForPlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FootballApp.Models.Druzyna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Druzyny");
                });

            modelBuilder.Entity("FootballApp.Models.Mecz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("DruzynaDomowaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DruzynaGościId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WynikDomowy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WynikGości")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DruzynaDomowaId");

                    b.HasIndex("DruzynaGościId");

                    b.ToTable("Mecze");
                });

            modelBuilder.Entity("FootballApp.Models.StatystykiZawodnika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Asysty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mecze")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZawodnikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZawodnikId")
                        .IsUnique();

                    b.ToTable("StatystykiZawodnikow");
                });

            modelBuilder.Entity("FootballApp.Models.Zawodnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DruzynaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pozycja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DruzynaId");

                    b.ToTable("Zawodnicy");
                });

            modelBuilder.Entity("FootballApp.Models.Mecz", b =>
                {
                    b.HasOne("FootballApp.Models.Druzyna", "DruzynaDomowa")
                        .WithMany("MeczeDomowe")
                        .HasForeignKey("DruzynaDomowaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballApp.Models.Druzyna", "DruzynaGości")
                        .WithMany("MeczeGości")
                        .HasForeignKey("DruzynaGościId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DruzynaDomowa");

                    b.Navigation("DruzynaGości");
                });

            modelBuilder.Entity("FootballApp.Models.StatystykiZawodnika", b =>
                {
                    b.HasOne("FootballApp.Models.Zawodnik", "Zawodnik")
                        .WithOne("Statystyki")
                        .HasForeignKey("FootballApp.Models.StatystykiZawodnika", "ZawodnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zawodnik");
                });

            modelBuilder.Entity("FootballApp.Models.Zawodnik", b =>
                {
                    b.HasOne("FootballApp.Models.Druzyna", "Druzyna")
                        .WithMany("Zawodnicy")
                        .HasForeignKey("DruzynaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Druzyna");
                });

            modelBuilder.Entity("FootballApp.Models.Druzyna", b =>
                {
                    b.Navigation("MeczeDomowe");

                    b.Navigation("MeczeGości");

                    b.Navigation("Zawodnicy");
                });

            modelBuilder.Entity("FootballApp.Models.Zawodnik", b =>
                {
                    b.Navigation("Statystyki")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
